### ISSUE TITLE
Which license ?

### ISSUE THREAD

**Issue by tenzap** [ser-gik/smoothrescale#1]
Hello, Could you clarify/set the license of your code please ? Thank you

**Comment by ser-gik** [comment]
Hey @tenzap!
This was just a demo project so I didn't really think about licensing.
I'd prefer to make my code to be 2-clause BSD. Keeping in mind that this demo depends on FFmpeg, which is LGPLv2.1+ the next must be satisfied to not violate FFmpeg license:
- dynamic linking to FFmpeg shared libraries (so that users can freely replace LGPLed FFmpeg)
- no GPL dependencies in used FFmpeg code (otherwise GPL goes up and makes both FFmpeg and smoothrescale to be GPL)

In the current state this project meets both requirements. If you are still interested - let me know, I'll sprinkle all files with
```
// SPDX-License-Identifier: BSD-2-Clause
``` 
and add `COPYING` to the root with the following
```
Copyright (c) 2016 Sergey Guralnik. All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the
    following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
    following disclaimer in the documentation and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR 
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND 
FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF 
USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY 
WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```
also there will be a notice about FFmpeg and how to treat it to stay with BSD.

**Comment by tenzap** [comment]
My project is GPLv3 and I wanted to use part of your code (mainly the jni / C code and the java related Class) to resize pictures and probably adapt it a little bit.
So I think BSD would be ok.

**Comment by ser-gik** [comment]
Here it is https://github.com/ser-gik/smoothrescale/commit/fdd3d5c4335fe0ead3edc6f26a5e4df1dbbc42a4
Thanks for your interest!

**Comment by tenzap** [comment]
thanks
